name: Release
on:
  push:
    tags:
      - "v*"
      - "!v*-rc*"

permissions:
  contents: write
jobs:
  pre_release_lmmg:
    name: Publish Release LMMG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Build ZIP file
        run: |
          mkdir -p Packages-Out/
          7z a ../Packages-Out/vikingstudios-airport-lmmg-xewkija.zip ./Packages/vikingstudios-airport-lmmg-xewkija/
          cd ../..
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2.0.4    
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          files: ../Packages-Out/vikingstudios-airport-lmmg-xewkija.zip
